services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_DB: device_db
      POSTGRES_USER: device
      POSTGRES_PASSWORD: device
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U device -d device_db"]
      interval: 10s
      timeout: 5s
      retries: 5