services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_DB: device_db
      POSTGRES_USER: device
      POSTGRES_PASSWORD: device
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U device -d device_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  device-app:
    image: device-app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - device-app:1.0.0
    environment:
      DB_NAME: device_db
      DB_HOST: postgres
      DB_USER: device
      DB_PASSWORD: device
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy